using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;

namespace Bytes.Exchange
{
    /// This is the proxy class that is automatically generated by proxy genarator tool for cms.
    /// </summary>
    public partial class RegistrationProxy : DuplexClientBase<IRegistration>, IRegistration
    {

        public RegistrationProxy(System.ServiceModel.InstanceContext callbackInstance)
            : base(callbackInstance)
        {
        }

        public RegistrationProxy(System.ServiceModel.InstanceContext callbackInstance,
            string endpointConfigurationName)
            : base(callbackInstance, endpointConfigurationName)
        {
        }

        public RegistrationProxy(System.ServiceModel.InstanceContext callbackInstance,
            string endpointConfigurationName, string remoteAddress)
            : base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public RegistrationProxy(System.ServiceModel.InstanceContext callbackInstance,
            string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            : base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public RegistrationProxy(System.ServiceModel.InstanceContext callbackInstance,
            System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            : base(callbackInstance, binding, remoteAddress)
        {
        }

        #region IRegistration Members

        string[] IRegistration.Register(string registerInfo)
        {
            return base.Channel.Register(registerInfo);
        }

        void IRegistration.UnRegister()
        {
            base.Channel.UnRegister();
        }

        void IRegistration.SetBytes(byte[] bytes)
        {
            base.Channel.SetBytes(bytes);
        }

        #endregion
    }

}
