<?xml version="1.0" encoding="utf-8"?><Database Name="AstronomyExpress" Class="DataWarehouseLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=3D_MONSTR\SQLEXPRESS;Initial Catalog=AstronomyExpress;Integrated Security=True" SettingsObjectName="SQLServerWarehouse.Properties.Settings" SettingsPropertyName="AstronomyExpressConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BinaryTable" Member="BinaryTables">
    <Type Name="BinaryTable">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Length" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Ext" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="BinaryTree_BinaryTable" Member="BinaryTree" ThisKey="ParentId" OtherKey="Id" Type="BinaryTree" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BinaryTree" Member="BinaryTrees">
    <Type Name="BinaryTree">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="ext" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="BinaryTree_BinaryTable" Member="BinaryTables" ThisKey="Id" OtherKey="ParentId" Type="BinaryTable" />
      <Association Name="BinaryTree_BinaryTree" Member="BinaryTrees" ThisKey="Id" OtherKey="ParentId" Type="BinaryTree" />
      <Association Name="BinaryTree_BinaryTree" Member="BinaryTree1" ThisKey="ParentId" OtherKey="Id" Type="BinaryTree" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteBinary" Method="DeleteBinary">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBinaryTree" Method="DeleteBinaryTree">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectBinaryTree" Method="SelectBinaryTree">
    <ElementType Name="SelectBinaryTreeResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="ext" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertBinary" Method="InsertBinary">
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Data" Parameter="data" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="Length" Parameter="length" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ext" Parameter="ext" Type="System.String" DbType="Char(10)" />
    <ElementType Name="InsertBinaryResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertBinaryInterface" Method="InsertBinaryInterface">
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Data" Parameter="data" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="Length" Parameter="length" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ext" Parameter="ext" Type="System.String" DbType="Char(10)" />
    <Parameter Name="InterfaceName" Parameter="interfaceName" Type="System.String" DbType="VarChar(100)" />
  </Function>
  <Function Name="dbo.InsertBinaryNode" Method="InsertBinaryNode">
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="ext" Type="System.String" DbType="Char(10)" />
    <ElementType Name="InsertBinaryNodeResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectBinary" Method="SelectBinary">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="SelectBinaryResult">
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
      <Column Name="Ext" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectBinaryContents" Method="SelectBinaryContents">
    <Parameter Name="Ext" Parameter="ext" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="SelectBinaryContentsResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectBinaryTable" Method="SelectBinaryTable">
    <ElementType Name="SelectBinaryTableResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Ext" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateBinaryData" Method="UpdateBinaryData">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Data" Parameter="data" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBinaryTreeName" Method="UpdateBinaryTreeName">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBinaryTableDescription" Method="UpdateBinaryTableDescription">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(300)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBinaryTableName" Method="UpdateBinaryTableName">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBinaryTreeDescription" Method="UpdateBinaryTreeDescription">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(300)" />
    <Return Type="System.Int32" />
  </Function>
</Database>