//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agriculture.ScadaSample.WindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agriculture.ScadaSample.WindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Scada&gt;
        ///  &lt;Inputs&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Forced.X&lt;/Name&gt;
        ///      &lt;Value&gt;System.Double&lt;/Value&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Forced.Y&lt;/Name&gt;
        ///      &lt;Value&gt;System.Double&lt;/Value&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/Inputs&gt;
        ///  &lt;Outputs&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Forced.X&lt;/Name&gt;
        ///      &lt;Value&gt;System.Double&lt;/Value&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;Forced.Y&lt;/Name&gt;
        ///      &lt;Value&gt;System.Double&lt;/Value&gt;
        ///    &lt;/Item&gt;
        ///    &lt;Item&gt;
        ///      &lt;Name&gt;F.Formula_1&lt;/Name&gt;
        ///      &lt;Value&gt;System.D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string scada {
            get {
                return ResourceManager.GetString("scada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SCADA_Test {
            get {
                object obj = ResourceManager.GetObject("SCADA_Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
