//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulink.Proxy {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDesktop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDesktop() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simulink.Proxy.ResourceDesktop", typeof(ResourceDesktop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Gain {
            get {
                object obj = ResourceManager.GetObject("Gain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Mapping&gt;
        ///  &lt;Block BlockType=&quot;Sin&quot;&gt;
        ///    &lt;Aliases&gt;
        ///      &lt;Alias Name=&quot;Amplitude&quot; alias=&quot;a&quot;/&gt;
        ///      &lt;Alias Name=&quot;Frequency&quot; alias=&quot;f&quot;/&gt;
        ///    &lt;/Aliases&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block BlockType=&quot;Gain&quot;&gt;
        ///    &lt;Aliases&gt;
        ///      &lt;Alias Name=&quot;Gain&quot; alias=&quot;k&quot;/&gt;
        ///    &lt;/Aliases&gt;
        ///  &lt;/Block&gt;
        ///  &lt;Block BlockType=&quot;TransferFcn&quot;&gt;
        ///    &lt;Aliases&gt;
        ///      &lt;Alias Name=&quot;n0&quot; alias=&quot;k&quot;/&gt;
        ///      &lt;Alias Name=&quot;n1&quot; alias=&quot;l&quot;/&gt;
        ///      &lt;Alias Name=&quot;n2&quot; alias=&quot;m&quot;/&gt;
        ///      &lt;Alias Name=&quot;n3&quot; alias=&quot;n&quot;/&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Sin {
            get {
                object obj = ResourceManager.GetObject("Sin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Sum {
            get {
                object obj = ResourceManager.GetObject("Sum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] TransferFcn {
            get {
                object obj = ResourceManager.GetObject("TransferFcn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TransferFcn&gt;
        ///  &lt;Polynoms Type=&quot;Nominators&quot;&gt;
        ///    &lt;Formula Degree=&quot;0&quot;&gt;
        ///      &lt;Root&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.SimpleSymbol&quot; symbol=&quot;k&quot; S=&quot;k&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///            &lt;F /&gt;
        ///          &lt;/S&gt;
        ///        &lt;/F&gt;
        ///      &lt;/Root&gt;
        ///    &lt;/Formula&gt;
        ///    &lt;Formula Degree=&quot;1&quot;&gt;
        ///      &lt;Root&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.SimpleSymbol&quot; symbol=&quot;l&quot; S=&quot;l&quot; Type=&quot;1&quot; Index=&quot;1&quot; Leve [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TransferFcnMapping {
            get {
                return ResourceManager.GetString("TransferFcnMapping", resourceCulture);
            }
        }
    }
}
