//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPerformer.UI.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControl_Ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControl_Ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataPerformer.UI.Utils.ResourceControl_Ru", typeof(ResourceControl_Ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функция - аккумулятор.
        /// </summary>
        internal static string Accumulator_function {
            get {
                return ResourceManager.GetString("Accumulator_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Адамса.
        /// </summary>
        internal static string AdamsAPOSTROFF_method {
            get {
                return ResourceManager.GetString("AdamsAPOSTROFF_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимация.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограниченный.
        /// </summary>
        internal static string Bounded {
            get {
                return ResourceManager.GetString("Bounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комбинированная выборка.
        /// </summary>
        internal static string Combined_selection {
            get {
                return ResourceManager.GetString("Combined_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычислитель производных.
        /// </summary>
        internal static string Derivation_calculator {
            get {
                return ResourceManager.GetString("Derivation_calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок производной.
        /// </summary>
        internal static string Derivation_order {
            get {
                return ResourceManager.GetString("Derivation_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система дифференциальных уравнений.
        /// </summary>
        internal static string Differential_equation_system {
            get {
                return ResourceManager.GetString("Differential_equation_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дифференцальные уравнения.
        /// </summary>
        internal static string Differential_equations {
            get {
                return ResourceManager.GetString("Differential_equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Эйлера.
        /// </summary>
        internal static string Euler_method {
            get {
                return ResourceManager.GetString("Euler_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя события.
        /// </summary>
        internal static string Event_name {
            get {
                return ResourceManager.GetString("Event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Xml файл.
        /// </summary>
        internal static string Export_to_Xml {
            get {
                return ResourceManager.GetString("Export_to_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формулы выбраны. Выберите констаны, ставя галочки.
        /// </summary>
        internal static string Formulas_are_acceptedPOINT__Select_constants_using_checkboxes {
            get {
                return ResourceManager.GetString("Formulas_are_acceptedPOINT_ Select_constants_using_checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный преобразователь измерений.
        /// </summary>
        internal static string Function_consumer {
            get {
                return ResourceManager.GetString("Function_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы функций |*.xml.
        /// </summary>
        internal static string Function_files_ORSTARPOINTxml {
            get {
                return ResourceManager.GetString("Function_files_ORSTARPOINTxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт из Xml файла.
        /// </summary>
        internal static string Import_from_Xml {
            get {
                return ResourceManager.GetString("Import_from_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальные условия.
        /// </summary>
        internal static string Initial_conditions {
            get {
                return ResourceManager.GetString("Initial_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интенсивность.
        /// </summary>
        internal static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степень интерполяции.
        /// </summary>
        internal static string Interpolation_degree {
            get {
                return ResourceManager.GetString("Interpolation_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инверсия оси абсцисс.
        /// </summary>
        internal static string Invert_x_DEFIS_axis {
            get {
                return ResourceManager.GetString("Invert_x_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инверсия оси ординат.
        /// </summary>
        internal static string Invert_y_DEFIS_axis {
            get {
                return ResourceManager.GetString("Invert_y_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с преобразователем объектов.
        /// </summary>
        internal static string Link_of_object_transformer {
            get {
                return ResourceManager.GetString("Link_of_object_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преобразователь объектов.
        /// </summary>
        internal static string Object_transformer {
            get {
                return ResourceManager.GetString("Object_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За границами области определения.
        /// </summary>
        internal static string Outside_domain {
            get {
                return ResourceManager.GetString("Outside_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекурсивный элемент.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекурсивные соотношения.
        /// </summary>
        internal static string Recursive_relations {
            get {
                return ResourceManager.GetString("Recursive_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регрессия.
        /// </summary>
        internal static string Regression {
            get {
                return ResourceManager.GetString("Regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уравнения регрессии.
        /// </summary>
        internal static string Regression_equations {
            get {
                return ResourceManager.GetString("Regression_equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регрессионная связь.
        /// </summary>
        internal static string Regression_link {
            get {
                return ResourceManager.GetString("Regression_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры регрессии.
        /// </summary>
        internal static string Regression_parameters {
            get {
                return ResourceManager.GetString("Regression_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторяющаяся серия.
        /// </summary>
        internal static string Repeating_series {
            get {
                return ResourceManager.GetString("Repeating_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Рунге - Кутта.
        /// </summary>
        internal static string Runge_DEFIS_Kutta_method {
            get {
                return ResourceManager.GetString("Runge_DEFIS_Kutta_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График пока что не расчитан.
        /// </summary>
        internal static string Series_is_not_calculated_yet {
            get {
                return ResourceManager.GetString("Series_is_not_calculated_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать данные.
        /// </summary>
        internal static string Show_data {
            get {
                return ResourceManager.GetString("Show_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma0 =.
        /// </summary>
        internal static string Sigma0_EQUALS {
            get {
                return ResourceManager.GetString("Sigma0_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт анимации.
        /// </summary>
        internal static string Start_animation {
            get {
                return ResourceManager.GetString("Start_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество шагов.
        /// </summary>
        internal static string Step_count {
            get {
                return ResourceManager.GetString("Step_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановлен.
        /// </summary>
        internal static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с переключателем.
        /// </summary>
        internal static string Switch_link {
            get {
                return ResourceManager.GetString("Switch_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизировать график.
        /// </summary>
        internal static string Synchronize_graph {
            get {
                return ResourceManager.GetString("Synchronize_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табличная зависимость от двух параметров.
        /// </summary>
        internal static string Table_dependency_of_two_parameters {
            get {
                return ResourceManager.GetString("Table_dependency_of_two_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборка таблицы базы данных.
        /// </summary>
        internal static string Table_selection {
            get {
                return ResourceManager.GetString("Table_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логическая формула задачи.
        /// </summary>
        internal static string Task_logical_formula {
            get {
                return ResourceManager.GetString("Task_logical_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время в качестве аргумента.
        /// </summary>
        internal static string Time_as_argument {
            get {
                return ResourceManager.GetString("Time_as_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с одномерной функцией .
        /// </summary>
        internal static string Unary_link {
            get {
                return ResourceManager.GetString("Unary_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять ось х как.
        /// </summary>
        internal static string Use_x_axis_as {
            get {
                return ResourceManager.GetString("Use_x_axis_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять ось y как.
        /// </summary>
        internal static string Use_y_axis_as {
            get {
                return ResourceManager.GetString("Use_y_axis_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Векторный преобразователь фигур.
        /// </summary>
        internal static string Vector_formula_transformer {
            get {
                return ResourceManager.GetString("Vector_formula_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вектор - функция.
        /// </summary>
        internal static string Vector_perfomer {
            get {
                return ResourceManager.GetString("Vector_perfomer", resourceCulture);
            }
        }
    }
}
