//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPerformer.UI.Utils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControl_Ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControl_Ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataPerformer.UI.Utils.ResourceControl_Ru", typeof(ResourceControl_Ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция - аккумулятор.
        /// </summary>
        internal static string Accumulator_function {
            get {
                return ResourceManager.GetString("Accumulator_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Адамса.
        /// </summary>
        internal static string AdamsAPOSTROFF_method {
            get {
                return ResourceManager.GetString("AdamsAPOSTROFF_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анимация.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограниченный.
        /// </summary>
        internal static string Bounded {
            get {
                return ResourceManager.GetString("Bounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комбинированная выборка.
        /// </summary>
        internal static string Combined_selection {
            get {
                return ResourceManager.GetString("Combined_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычислитель производных.
        /// </summary>
        internal static string Derivation_calculator {
            get {
                return ResourceManager.GetString("Derivation_calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порядок производной.
        /// </summary>
        internal static string Derivation_order {
            get {
                return ResourceManager.GetString("Derivation_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система дифференциальных уравнений.
        /// </summary>
        internal static string Differential_equation_system {
            get {
                return ResourceManager.GetString("Differential_equation_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дифференцальные уравнения.
        /// </summary>
        internal static string Differential_equations {
            get {
                return ResourceManager.GetString("Differential_equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Эйлера.
        /// </summary>
        internal static string Euler_method {
            get {
                return ResourceManager.GetString("Euler_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя события.
        /// </summary>
        internal static string Event_name {
            get {
                return ResourceManager.GetString("Event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в Xml файл.
        /// </summary>
        internal static string Export_to_Xml {
            get {
                return ResourceManager.GetString("Export_to_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формулы выбраны. Выберите констаны, ставя галочки.
        /// </summary>
        internal static string Formulas_are_acceptedPOINT__Select_constants_using_checkboxes {
            get {
                return ResourceManager.GetString("Formulas_are_acceptedPOINT_ Select_constants_using_checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функциональный преобразователь измерений.
        /// </summary>
        internal static string Function_consumer {
            get {
                return ResourceManager.GetString("Function_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы функций |*.xml.
        /// </summary>
        internal static string Function_files_ORSTARPOINTxml {
            get {
                return ResourceManager.GetString("Function_files_ORSTARPOINTxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт из Xml файла.
        /// </summary>
        internal static string Import_from_Xml {
            get {
                return ResourceManager.GetString("Import_from_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальные условия.
        /// </summary>
        internal static string Initial_conditions {
            get {
                return ResourceManager.GetString("Initial_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность.
        /// </summary>
        internal static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Степень интерполяции.
        /// </summary>
        internal static string Interpolation_degree {
            get {
                return ResourceManager.GetString("Interpolation_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инверсия оси абсцисс.
        /// </summary>
        internal static string Invert_x_DEFIS_axis {
            get {
                return ResourceManager.GetString("Invert_x_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инверсия оси ординат.
        /// </summary>
        internal static string Invert_y_DEFIS_axis {
            get {
                return ResourceManager.GetString("Invert_y_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с преобразователем объектов.
        /// </summary>
        internal static string Link_of_object_transformer {
            get {
                return ResourceManager.GetString("Link_of_object_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразователь объектов.
        /// </summary>
        internal static string Object_transformer {
            get {
                return ResourceManager.GetString("Object_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За границами области определения.
        /// </summary>
        internal static string Outside_domain {
            get {
                return ResourceManager.GetString("Outside_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекурсивный элемент.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекурсивные соотношения.
        /// </summary>
        internal static string Recursive_relations {
            get {
                return ResourceManager.GetString("Recursive_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регрессия.
        /// </summary>
        internal static string Regression {
            get {
                return ResourceManager.GetString("Regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уравнения регрессии.
        /// </summary>
        internal static string Regression_equations {
            get {
                return ResourceManager.GetString("Regression_equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регрессионная связь.
        /// </summary>
        internal static string Regression_link {
            get {
                return ResourceManager.GetString("Regression_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры регрессии.
        /// </summary>
        internal static string Regression_parameters {
            get {
                return ResourceManager.GetString("Regression_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторяющаяся серия.
        /// </summary>
        internal static string Repeating_series {
            get {
                return ResourceManager.GetString("Repeating_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Рунге - Кутта.
        /// </summary>
        internal static string Runge_DEFIS_Kutta_method {
            get {
                return ResourceManager.GetString("Runge_DEFIS_Kutta_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График пока что не расчитан.
        /// </summary>
        internal static string Series_is_not_calculated_yet {
            get {
                return ResourceManager.GetString("Series_is_not_calculated_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать данные.
        /// </summary>
        internal static string Show_data {
            get {
                return ResourceManager.GetString("Show_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sigma0 =.
        /// </summary>
        internal static string Sigma0_EQUALS {
            get {
                return ResourceManager.GetString("Sigma0_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт анимации.
        /// </summary>
        internal static string Start_animation {
            get {
                return ResourceManager.GetString("Start_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество шагов.
        /// </summary>
        internal static string Step_count {
            get {
                return ResourceManager.GetString("Step_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приостановлен.
        /// </summary>
        internal static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с переключателем.
        /// </summary>
        internal static string Switch_link {
            get {
                return ResourceManager.GetString("Switch_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синхронизировать график.
        /// </summary>
        internal static string Synchronize_graph {
            get {
                return ResourceManager.GetString("Synchronize_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Табличная зависимость от двух параметров.
        /// </summary>
        internal static string Table_dependency_of_two_parameters {
            get {
                return ResourceManager.GetString("Table_dependency_of_two_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выборка таблицы базы данных.
        /// </summary>
        internal static string Table_selection {
            get {
                return ResourceManager.GetString("Table_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логическая формула задачи.
        /// </summary>
        internal static string Task_logical_formula {
            get {
                return ResourceManager.GetString("Task_logical_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время в качестве аргумента.
        /// </summary>
        internal static string Time_as_argument {
            get {
                return ResourceManager.GetString("Time_as_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с одномерной функцией .
        /// </summary>
        internal static string Unary_link {
            get {
                return ResourceManager.GetString("Unary_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взять ось х как.
        /// </summary>
        internal static string Use_x_axis_as {
            get {
                return ResourceManager.GetString("Use_x_axis_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взять ось y как.
        /// </summary>
        internal static string Use_y_axis_as {
            get {
                return ResourceManager.GetString("Use_y_axis_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Векторный преобразователь фигур.
        /// </summary>
        internal static string Vector_formula_transformer {
            get {
                return ResourceManager.GetString("Vector_formula_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вектор - функция.
        /// </summary>
        internal static string Vector_perfomer {
            get {
                return ResourceManager.GetString("Vector_perfomer", resourceCulture);
            }
        }
    }
}
