//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collada.Converters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Collada.Converters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;effect id=&quot;effect-a2431cff_dds&quot;&gt;
        ///
        ///
        ///		&lt;profile_COMMON&gt;
        ///
        ///
        ///			&lt;newparam sid=&quot;DiffuseColor-surface&quot;&gt;
        ///
        ///
        ///				&lt;surface type=&quot;2D&quot;&gt;
        ///
        ///					&lt;init_from&gt;object_1&lt;/init_from&gt;
        ///
        ///				&lt;/surface&gt;
        ///
        ///			&lt;/newparam&gt;
        ///
        ///
        ///			&lt;newparam sid=&quot;DiffuseColor-sampler&quot;&gt;
        ///
        ///
        ///				&lt;sampler2D&gt;
        ///
        ///					&lt;source&gt;DiffuseColor-surface&lt;/source&gt;
        ///
        ///					&lt;wrap_s&gt;WRAP&lt;/wrap_s&gt;
        ///
        ///					&lt;wrap_t&gt;WRAP&lt;/wrap_t&gt;
        ///
        ///					&lt;wrap_p&gt;WRAP&lt;/wrap_p&gt;
        ///
        ///					&lt;minfilter&gt;NONE&lt;/minfilter&gt;
        ///
        ///					&lt;magfilter&gt;NONE&lt;/magfilter&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string effect {
            get {
                return ResourceManager.GetString("effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        ///	&lt;asset&gt;
        ///			&lt;contributor&gt;
        ///				&lt;author&gt;&lt;/author&gt;
        ///				&lt;authoring_tool&gt;&lt;/authoring_tool&gt;
        ///				&lt;comments&gt;&lt;/comments&gt;
        ///				&lt;copyright&gt;&lt;/copyright&gt;
        ///			&lt;/contributor&gt;
        ///			&lt;created&gt;&lt;/created&gt;
        ///			&lt;modified&gt;&lt;/modified&gt;
        ///			&lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///			&lt;unit meter=&quot;1.0&quot; name=&quot;meter&quot;/&gt;
        ///		&lt;unit meter=&quot;1&quot; /&gt;
        ///    &lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///  &lt;/asset&gt;
        ///  &lt;library_lights /&gt;
        ///  &lt;library_materials&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string etalon2005 {
            get {
                return ResourceManager.GetString("etalon2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA version=&quot;1.5.0&quot; xmlns=&quot;http://www.collada.org/2008/03/COLLADASchema&quot;&gt;
        ///	&lt;asset&gt;
        ///		&lt;contributor&gt;
        ///			&lt;author&gt;&lt;/author&gt;
        ///			&lt;authoring_tool&gt;&lt;/authoring_tool&gt;
        ///			&lt;comments&gt;&lt;/comments&gt;
        ///			&lt;copyright&gt;&lt;/copyright&gt;
        ///		&lt;/contributor&gt;
        ///		&lt;created&gt;&lt;/created&gt;
        ///		&lt;modified&gt;&lt;/modified&gt;
        ///		&lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///		&lt;unit meter=&quot;1.0&quot; name=&quot;meter&quot;/&gt;
        ///		&lt;unit meter=&quot;1&quot; /&gt;
        ///		&lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///	&lt;/asset&gt;
        ///	&lt;library_lights /&gt;
        ///  &lt;library_materials&gt;
        ///  &lt;/library_materi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string etalon2008 {
            get {
                return ResourceManager.GetString("etalon2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ModelVisual3D xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;&lt;/ModelVisual3D&gt;
        ///
        ///.
        /// </summary>
        internal static string xaml {
            get {
                return ResourceManager.GetString("xaml", resourceCulture);
            }
        }
    }
}
