//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motion6D.UI.Utils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControl_Ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControl_Ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motion6D.UI.Utils.ResourceControl_Ru", typeof(ResourceControl_Ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абсолютная система координат.
        /// </summary>
        internal static string Absolute_reference_frame {
            get {
                return ResourceManager.GetString("Absolute_reference_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поглощающий материал.
        /// </summary>
        internal static string Absorbing_layer {
            get {
                return ResourceManager.GetString("Absorbing_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компоненты ускорения.
        /// </summary>
        internal static string Acceleration_components {
            get {
                return ResourceManager.GetString("Acceleration_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фигура - агрегат.
        /// </summary>
        internal static string Aggregate_figure {
            get {
                return ResourceManager.GetString("Aggregate_figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аналитическая фигура.
        /// </summary>
        internal static string Analitical_Figure {
            get {
                return ResourceManager.GetString("Analitical_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Антенна.
        /// </summary>
        internal static string Antenna {
            get {
                return ResourceManager.GetString("Antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площадь.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Астрономия + OpenGL.
        /// </summary>
        internal static string Astronomy_PLUS_OpenGL {
            get {
                return ResourceManager.GetString("Astronomy_PLUS_OpenGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Барицентрическое разделение.
        /// </summary>
        internal static string Barycentric_division {
            get {
                return ResourceManager.GetString("Barycentric_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовое расстояние, м.
        /// </summary>
        internal static string BaseCOMMA_m {
            get {
                return ResourceManager.GetString("BaseCOMMA_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D Визуализатор.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер окна камеры.
        /// </summary>
        internal static string Camera_size {
            get {
                return ResourceManager.GetString("Camera_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Облучаемый 3D объект.
        /// </summary>
        internal static string Consumer_of_THREED_field {
            get {
                return ResourceManager.GetString("Consumer_of_THREED_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координата.
        /// </summary>
        internal static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ковариантный.
        /// </summary>
        internal static string Covariant {
            get {
                return ResourceManager.GetString("Covariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать фильм.
        /// </summary>
        internal static string Create_Film {
            get {
                return ResourceManager.GetString("Create_Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрическая привязка, связанная с источником данных.
        /// </summary>
        internal static string Data_frame {
            get {
                return ResourceManager.GetString("Data_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Множество точек генерируемое из базы данных.
        /// </summary>
        internal static string Data_points_collection {
            get {
                return ResourceManager.GetString("Data_points_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трёхмерные фигуры базы данных.
        /// </summary>
        internal static string Database_shapes {
            get {
                return ResourceManager.GetString("Database_shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деформированный объект.
        /// </summary>
        internal static string Deformed_object {
            get {
                return ResourceManager.GetString("Deformed_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диполь.
        /// </summary>
        internal static string Dipole {
            get {
                return ResourceManager.GetString("Dipole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доплеровская связь.
        /// </summary>
        internal static string Doppler_frame_link {
            get {
                return ResourceManager.GetString("Doppler_frame_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доплеровские измерения.
        /// </summary>
        internal static string Doppler_measurements {
            get {
                return ResourceManager.GetString("Doppler_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доплеровская связь с облучаемым объектом.
        /// </summary>
        internal static string Doppler_object_link {
            get {
                return ResourceManager.GetString("Doppler_object_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля.
        /// </summary>
        internal static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЭД объекты.
        /// </summary>
        internal static string Electromagnetic_objects {
            get {
                return ResourceManager.GetString("Electromagnetic_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры поля.
        /// </summary>
        internal static string Field_parameters {
            get {
                return ResourceManager.GetString("Field_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя фигуры.
        /// </summary>
        internal static string Figure_name {
            get {
                return ResourceManager.GetString("Figure_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фигура, загружаемая из файла.
        /// </summary>
        internal static string File_figure {
            get {
                return ResourceManager.GetString("File_figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильм.
        /// </summary>
        internal static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директория фильма.
        /// </summary>
        internal static string Film_directory {
            get {
                return ResourceManager.GetString("Film_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Силы и моменты.
        /// </summary>
        internal static string Forces_and_moments {
            get {
                return ResourceManager.GetString("Forces_and_moments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Излучатель с диаграммой направленности, заданной формулой.
        /// </summary>
        internal static string Formula_diagram_radiation {
            get {
                return ResourceManager.GetString("Formula_diagram_radiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразованная трёхмерная фигура.
        /// </summary>
        internal static string Formula_figure_transformation {
            get {
                return ResourceManager.GetString("Formula_figure_transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с трёхмерным преобразователем.
        /// </summary>
        internal static string Formula_transformer_link {
            get {
                return ResourceManager.GetString("Formula_transformer_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жёсткая геометрическая связь.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функциональная геометрическая связь.
        /// </summary>
        internal static string Functional_geometric_link {
            get {
                return ResourceManager.GetString("Functional_geometric_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрические связи.
        /// </summary>
        internal static string Geometric_links {
            get {
                return ResourceManager.GetString("Geometric_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрические объекты.
        /// </summary>
        internal static string Geometric_objects {
            get {
                return ResourceManager.GetString("Geometric_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрия.
        /// </summary>
        internal static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрическая связь.
        /// </summary>
        internal static string Geometry_link {
            get {
                return ResourceManager.GetString("Geometry_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гравитационнное поле.
        /// </summary>
        internal static string Gravity_field {
            get {
                return ResourceManager.GetString("Gravity_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рыскание.
        /// </summary>
        internal static string Hunting {
            get {
                return ResourceManager.GetString("Hunting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взять за начало отсчёта.
        /// </summary>
        internal static string Link_betveen_coordinate_center_and_user_object {
            get {
                return ResourceManager.GetString("Link_betveen_coordinate_center_and_user_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь антенны с источником данных.
        /// </summary>
        internal static string Link_between_antenn_and_data_source {
            get {
                return ResourceManager.GetString("Link_between_antenn_and_data_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь антенны с излучателем.
        /// </summary>
        internal static string Link_between_antenn_and_radiator {
            get {
                return ResourceManager.GetString("Link_between_antenn_and_radiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь картики и камеры.
        /// </summary>
        internal static string Link_between_bitmap_selection_and_camera {
            get {
                return ResourceManager.GetString("Link_between_bitmap_selection_and_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между полем и его потребителем.
        /// </summary>
        internal static string Link_between_field_and_its_consumer {
            get {
                return ResourceManager.GetString("Link_between_field_and_its_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь формулы с графическим источником данных.
        /// </summary>
        internal static string Link_between_formula_and_graph_source {
            get {
                return ResourceManager.GetString("Link_between_formula_and_graph_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между формулой и источником излучения.
        /// </summary>
        internal static string Link_between_formula_and_radiator {
            get {
                return ResourceManager.GetString("Link_between_formula_and_radiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь формулы с трансформером.
        /// </summary>
        internal static string Link_between_formula_and_transformer {
            get {
                return ResourceManager.GetString("Link_between_formula_and_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между механическими агрегатами.
        /// </summary>
        internal static string Link_between_mechanical_aggregates {
            get {
                return ResourceManager.GetString("Link_between_mechanical_aggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь c фигурой - агрегатом.
        /// </summary>
        internal static string Link_with_aggregate_figure {
            get {
                return ResourceManager.GetString("Link_with_aggregate_figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь геометрической привязки с источником данных.
        /// </summary>
        internal static string Link_with_data_frame {
            get {
                return ResourceManager.GetString("Link_with_data_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с потребителем 3D визуализации.
        /// </summary>
        internal static string Link_with_visual_consumer {
            get {
                return ResourceManager.GetString("Link_with_visual_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Визуальная связь.
        /// </summary>
        internal static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масса.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры материала.
        /// </summary>
        internal static string Material_parameters {
            get {
                return ResourceManager.GetString("Material_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материалы.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индикатор стационарной фазы.
        /// </summary>
        internal static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промах.
        /// </summary>
        internal static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции.
        /// </summary>
        internal static string Moment_of_inertia {
            get {
                return ResourceManager.GetString("Moment_of_inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент инерции и масса.
        /// </summary>
        internal static string Moment_of_inertia_and_mass {
            get {
                return ResourceManager.GetString("Moment_of_inertia_and_mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры движения.
        /// </summary>
        internal static string Motion_Parameters {
            get {
                return ResourceManager.GetString("Motion_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Движение, определяемое аналитической зависимостью.
        /// </summary>
        internal static string Moved_Formula_Frame {
            get {
                return ResourceManager.GetString("Moved_Formula_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подвижная система координат.
        /// </summary>
        internal static string Moved_frame {
            get {
                return ResourceManager.GetString("Moved_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормаль.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D файлы |*.gl,*.xaml.
        /// </summary>
        internal static string OpenGL_figure_files_ORSTARPOINTgl {
            get {
                return ResourceManager.GetString("OpenGL_figure_files_ORSTARPOINTgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трансформируемая фигура.
        /// </summary>
        internal static string Parent_figure {
            get {
                return ResourceManager.GetString("Parent_figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Q0.
        /// </summary>
        internal static string Q0 {
            get {
                return ResourceManager.GetString("Q0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Q1.
        /// </summary>
        internal static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Q2.
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Q3.
        /// </summary>
        internal static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угол обзора.
        /// </summary>
        internal static string Reference_angle {
            get {
                return ResourceManager.GetString("Reference_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угол обзора, град.
        /// </summary>
        internal static string Reference_angleCOMMA_deg {
            get {
                return ResourceManager.GetString("Reference_angleCOMMA_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измеритель относительного положения.
        /// </summary>
        internal static string Relative_measure {
            get {
                return ResourceManager.GetString("Relative_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с измерителем относительного положения.
        /// </summary>
        internal static string Relative_Measure_Link {
            get {
                return ResourceManager.GetString("Relative_Measure_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Относительные измерения.
        /// </summary>
        internal static string Relative_measurements {
            get {
                return ResourceManager.GetString("Relative_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь относительных измерений.
        /// </summary>
        internal static string Relative_measurements_link {
            get {
                return ResourceManager.GetString("Relative_measurements_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Относительная система координат.
        /// </summary>
        internal static string Relative_reference_frame {
            get {
                return ResourceManager.GetString("Relative_reference_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Репер.
        /// </summary>
        internal static string Reper {
            get {
                return ResourceManager.GetString("Reper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жёсткая геометрическая связь.
        /// </summary>
        internal static string Rigid_geometic_link {
            get {
                return ResourceManager.GetString("Rigid_geometic_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неподвижная система координат.
        /// </summary>
        internal static string Rigig_frame {
            get {
                return ResourceManager.GetString("Rigig_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ракета.
        /// </summary>
        internal static string Rocket {
            get {
                return ResourceManager.GetString("Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Крен.
        /// </summary>
        internal static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угол поворота.
        /// </summary>
        internal static string Rotation_angle {
            get {
                return ResourceManager.GetString("Rotation_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица перехода.
        /// </summary>
        internal static string Rotation_matrix {
            get {
                return ResourceManager.GetString("Rotation_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масштаб.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить значение угла.
        /// </summary>
        internal static string Set_angle {
            get {
                return ResourceManager.GetString("Set_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить углы.
        /// </summary>
        internal static string Set_angles {
            get {
                return ResourceManager.GetString("Set_angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить соответствие материалов.
        /// </summary>
        internal static string Set_materials {
            get {
                return ResourceManager.GetString("Set_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D объект.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D Формы.
        /// </summary>
        internal static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пространственное движение.
        /// </summary>
        internal static string SIXD_Motion {
            get {
                return ResourceManager.GetString("SIXD_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интеграл по телесному углу.
        /// </summary>
        internal static string Solid_angle_integral {
            get {
                return ResourceManager.GetString("Solid_angle_integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамика твёрдого тела.
        /// </summary>
        internal static string Solid_body_dynamics {
            get {
                return ResourceManager.GetString("Solid_body_dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь спектра с 3D объектом.
        /// </summary>
        internal static string Spectrum_figure_link {
            get {
                return ResourceManager.GetString("Spectrum_figure_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь спектра с излучателем.
        /// </summary>
        internal static string Spectrum_radiator_link {
            get {
                return ResourceManager.GetString("Spectrum_radiator_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сфера.
        /// </summary>
        internal static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммарное излучение.
        /// </summary>
        internal static string Sum_of_radiators {
            get {
                return ResourceManager.GetString("Sum_of_radiators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тангаж.
        /// </summary>
        internal static string Tangage {
            get {
                return ResourceManager.GetString("Tangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физическое полe в трёхмерном пространстве.
        /// </summary>
        internal static string Three_dimensional_field {
            get {
                return ResourceManager.GetString("Three_dimensional_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трёхмерное физическое поле.
        /// </summary>
        internal static string THREED_Field {
            get {
                return ResourceManager.GetString("THREED_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление 3D образов.
        /// </summary>
        internal static string THREED_Figure_restoration {
            get {
                return ResourceManager.GetString("THREED_Figure_restoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трёхмерный объект.
        /// </summary>
        internal static string THREED_Object {
            get {
                return ResourceManager.GetString("THREED_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трёхмерное преобразование фигуры.
        /// </summary>
        internal static string THREED_Transformation {
            get {
                return ResourceManager.GetString("THREED_Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица перехода.
        /// </summary>
        internal static string Tramsformation_matrix {
            get {
                return ResourceManager.GetString("Tramsformation_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cвязь c камерой.
        /// </summary>
        internal static string Visibility_link {
            get {
                return ResourceManager.GetString("Visibility_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ориентация линии визирования..
        /// </summary>
        internal static string Visibility_orientation {
            get {
                return ResourceManager.GetString("Visibility_orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Визуализация.
        /// </summary>
        internal static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
    }
}
