//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Engineering.Localization.Utils {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceControl_Ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceControl_Ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Engineering.Localization.Utils.ResourceControl_Ru", typeof(ResourceControl_Ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абсолютное время.
        /// </summary>
        internal static string Absolute_time {
            get {
                return ResourceManager.GetString("Absolute_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить выбор входных данных.
        /// </summary>
        internal static string Accept_dataDEFISin {
            get {
                return ResourceManager.GetString("Accept_dataDEFISin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить выбор размерности.
        /// </summary>
        internal static string Accept_dimension {
            get {
                return ResourceManager.GetString("Accept_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить количество.
        /// </summary>
        internal static string Accept_number {
            get {
                return ResourceManager.GetString("Accept_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активен.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить агрегацию.
        /// </summary>
        internal static string Aggregate {
            get {
                return ResourceManager.GetString("Aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агрегаты.
        /// </summary>
        internal static string Aggregates {
            get {
                return ResourceManager.GetString("Aggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда.
        /// </summary>
        internal static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аналитические формулы.
        /// </summary>
        internal static string Analytical_expressions {
            get {
                return ResourceManager.GetString("Analytical_expressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить выбор типа.
        /// </summary>
        internal static string Apply_type {
            get {
                return ResourceManager.GetString("Apply_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка рабочего поля.
        /// </summary>
        internal static string Check_desktop {
            get {
                return ResourceManager.GetString("Check_desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите компьютер и затем соединитесь (создайте) базу данных.
        /// </summary>
        internal static string Choose_a_host_and_then_connect_BRAcreateKET_database {
            get {
                return ResourceManager.GetString("Choose_a_host_and_then_connect_BRAcreateKET_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодирование.
        /// </summary>
        internal static string Coding {
            get {
                return ResourceManager.GetString("Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цветной.
        /// </summary>
        internal static string Colored {
            get {
                return ResourceManager.GetString("Colored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвета.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда.
        /// </summary>
        internal static string Command_Pane {
            get {
                return ResourceManager.GetString("Command_Pane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компоненты массива.
        /// </summary>
        internal static string Components_of_array {
            get {
                return ResourceManager.GetString("Components_of_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константы выбраны. Выберите переменные, используя выпадающие меню.
        /// </summary>
        internal static string Constants_are_accepetedPOINT_Select_dataDEFISin {
            get {
                return ResourceManager.GetString("Constants_are_accepetedPOINT_Select_dataDEFISin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование графика с рисунка.
        /// </summary>
        internal static string Copy_plot_from_picture {
            get {
                return ResourceManager.GetString("Copy_plot_from_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Крестики.
        /// </summary>
        internal static string Crosses {
            get {
                return ResourceManager.GetString("Crosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее время.
        /// </summary>
        internal static string Current_time {
            get {
                return ResourceManager.GetString("Current_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итератор базы данных.
        /// </summary>
        internal static string Data_set_iterator {
            get {
                return ResourceManager.GetString("Data_set_iterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник данных.
        /// </summary>
        internal static string Data_source {
            get {
                return ResourceManager.GetString("Data_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица данных.
        /// </summary>
        internal static string Data_table {
            get {
                return ResourceManager.GetString("Data_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График базы данных.
        /// </summary>
        internal static string Data_table_series {
            get {
                return ResourceManager.GetString("Data_table_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График базы данных.
        /// </summary>
        internal static string Database_graph {
            get {
                return ResourceManager.GetString("Database_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графики базы данных.
        /// </summary>
        internal static string Database_graphs {
            get {
                return ResourceManager.GetString("Database_graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входные данные.
        /// </summary>
        internal static string DataDEFISin {
            get {
                return ResourceManager.GetString("DataDEFISin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата (UTC) .
        /// </summary>
        internal static string Date_BRAUTCKET {
            get {
                return ResourceManager.GetString("Date_BRAUTCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата, время.
        /// </summary>
        internal static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата, время (UTC) .
        /// </summary>
        internal static string Date_Time_BRAUTCKET {
            get {
                return ResourceManager.GetString("Date_Time_BRAUTCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменные выбраны. Введите значения констант.
        /// </summary>
        internal static string DdataDEFISin__is_acceptedPOINT__Enter_values_of_constants {
            get {
                return ResourceManager.GetString("DdataDEFISin_ is_acceptedPOINT_ Enter_values_of_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяемые параметры.
        /// </summary>
        internal static string Defined_parameters {
            get {
                return ResourceManager.GetString("Defined_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производные параметры.
        /// </summary>
        internal static string Derived_parameters {
            get {
                return ResourceManager.GetString("Derived_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string Description_Pane {
            get {
                return ResourceManager.GetString("Description_Pane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диаграмма.
        /// </summary>
        internal static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Численные значения.
        /// </summary>
        internal static string Digital_values {
            get {
                return ResourceManager.GetString("Digital_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размерность:.
        /// </summary>
        internal static string DimensionCOLON {
            get {
                return ResourceManager.GetString("DimensionCOLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вниз.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рисование графика.
        /// </summary>
        internal static string Draw_series {
            get {
                return ResourceManager.GetString("Draw_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор значений переменных.
        /// </summary>
        internal static string Editor_of_values_of_variables {
            get {
                return ResourceManager.GetString("Editor_of_values_of_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coбытие.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешние объекты.
        /// </summary>
        internal static string External_Objects {
            get {
                return ResourceManager.GetString("External_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратная связь.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        internal static string File_name {
            get {
                return ResourceManager.GetString("File_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла:.
        /// </summary>
        internal static string File_nameCOLON {
            get {
                return ResourceManager.GetString("File_nameCOLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр - передаточная функция.
        /// </summary>
        internal static string Filter_DEFIS_transform_function {
            get {
                return ResourceManager.GetString("Filter_DEFIS_transform_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фиксированный шаг.
        /// </summary>
        internal static string Fixed_step {
            get {
                return ResourceManager.GetString("Fixed_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частотные характеристики.
        /// </summary>
        internal static string Frequency_characteristics {
            get {
                return ResourceManager.GetString("Frequency_characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота, Гц.
        /// </summary>
        internal static string FrequencyCOMMA_Hz {
            get {
                return ResourceManager.GetString("FrequencyCOMMA_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полная проверка.
        /// </summary>
        internal static string Full_check {
            get {
                return ResourceManager.GetString("Full_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генератор.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя графика.
        /// </summary>
        internal static string Graph_name {
            get {
                return ResourceManager.GetString("Graph_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графическое представление измерений.
        /// </summary>
        internal static string Graph_representation {
            get {
                return ResourceManager.GetString("Graph_representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Битовая карта - выборка.
        /// </summary>
        internal static string Graph_selection_bitmap {
            get {
                return ResourceManager.GetString("Graph_selection_bitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразование графиков.
        /// </summary>
        internal static string Graph_transform {
            get {
                return ResourceManager.GetString("Graph_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горизонтальный.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат индикации.
        /// </summary>
        internal static string Indication_format {
            get {
                return ResourceManager.GetString("Indication_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на уже определён.
        /// </summary>
        internal static string is_already_defined {
            get {
                return ResourceManager.GetString("is_already_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уточнить.
        /// </summary>
        internal static string Iterate {
            get {
                return ResourceManager.GetString("Iterate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с итератором.
        /// </summary>
        internal static string Iterator_link {
            get {
                return ResourceManager.GetString("Iterator_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графический итератор.
        /// </summary>
        internal static string Iterator_series {
            get {
                return ResourceManager.GetString("Iterator_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левая граница.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левая часть.
        /// </summary>
        internal static string Left_part {
            get {
                return ResourceManager.GetString("Left_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Обзор...&gt;.
        /// </summary>
        internal static string LESSBrowsePOINTPOINTPOINTMORE {
            get {
                return ResourceManager.GetString("LESSBrowsePOINTPOINTPOINTMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Тип кодирования&gt;.
        /// </summary>
        internal static string LESSCoding_typeMORE {
            get {
                return ResourceManager.GetString("LESSCoding_typeMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяемые параметры.
        /// </summary>
        internal static string LESSDefined_parametersMORE {
            get {
                return ResourceManager.GetString("LESSDefined_parametersMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Размерность&gt;.
        /// </summary>
        internal static string LESSDimensionMORE {
            get {
                return ResourceManager.GetString("LESSDimensionMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Точки&gt;.
        /// </summary>
        internal static string LESSPointsMORE {
            get {
                return ResourceManager.GetString("LESSPointsMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Тип графика&gt;.
        /// </summary>
        internal static string LESSSeries_typeMORE {
            get {
                return ResourceManager.GetString("LESSSeries_typeMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;График&gt;.
        /// </summary>
        internal static string LESSSeriesMORE {
            get {
                return ResourceManager.GetString("LESSSeriesMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь формулы с графическим источником данных.
        /// </summary>
        internal static string Link_between_formula_and_graph_source {
            get {
                return ResourceManager.GetString("Link_between_formula_and_graph_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с выборкой.
        /// </summary>
        internal static string Link_between_selection_and_selection_consumer {
            get {
                return ResourceManager.GetString("Link_between_selection_and_selection_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между сервером и клиентом таблицы базы данных.
        /// </summary>
        internal static string Link_between_table_provider_and_table_consumer {
            get {
                return ResourceManager.GetString("Link_between_table_provider_and_table_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сваязь с провайдером координатной оси.
        /// </summary>
        internal static string Link_between_vector_provider_and_user_object {
            get {
                return ResourceManager.GetString("Link_between_vector_provider_and_user_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь трансформатора объектов.
        /// </summary>
        internal static string Link_of_object_transformer {
            get {
                return ResourceManager.GetString("Link_of_object_transformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрические параметры связи.
        /// </summary>
        internal static string Link_parameters {
            get {
                return ResourceManager.GetString("Link_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простая проверка.
        /// </summary>
        internal static string Lite_check {
            get {
                return ResourceManager.GetString("Lite_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логарифмическая шкала.
        /// </summary>
        internal static string Logariphmic_scale {
            get {
                return ResourceManager.GetString("Logariphmic_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логарифмическая шкала.
        /// </summary>
        internal static string Logarithmic_scale {
            get {
                return ResourceManager.GetString("Logarithmic_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с источником измерений.
        /// </summary>
        internal static string Measurement_consumer_link {
            get {
                return ResourceManager.GetString("Measurement_consumer_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение.
        /// </summary>
        internal static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разное.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормализовать матрицу.
        /// </summary>
        internal static string Normalize_matrix {
            get {
                return ResourceManager.GetString("Normalize_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция обнуления.
        /// </summary>
        internal static string Nulling_function {
            get {
                return ResourceManager.GetString("Nulling_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер компонента.
        /// </summary>
        internal static string Number_of_component {
            get {
                return ResourceManager.GetString("Number_of_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество производных параметров.
        /// </summary>
        internal static string Number_of_derived_parameters {
            get {
                return ResourceManager.GetString("Number_of_derived_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица ODBC.
        /// </summary>
        internal static string ODBC_Table {
            get {
                return ResourceManager.GetString("ODBC_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдвиг.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить график.
        /// </summary>
        internal static string Open_graph {
            get {
                return ResourceManager.GetString("Open_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить график из XML файла.
        /// </summary>
        internal static string Open_XML_graph {
            get {
                return ResourceManager.GetString("Open_XML_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ориентация.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условие вывода.
        /// </summary>
        internal static string Output_condition {
            get {
                return ResourceManager.GetString("Output_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выходные параметры.
        /// </summary>
        internal static string Output_parameters {
            get {
                return ResourceManager.GetString("Output_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза.
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза, град.
        /// </summary>
        internal static string PhaseCOMMA_Deg {
            get {
                return ResourceManager.GetString("PhaseCOMMA_Deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарисовать.
        /// </summary>
        internal static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построение графиков.
        /// </summary>
        internal static string Plot_design {
            get {
                return ResourceManager.GetString("Plot_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индикация графиков.
        /// </summary>
        internal static string Plotter {
            get {
                return ResourceManager.GetString("Plotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры точки.
        /// </summary>
        internal static string Point_parameters {
            get {
                return ResourceManager.GetString("Point_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индикатор точек.
        /// </summary>
        internal static string Points_indicator {
            get {
                return ResourceManager.GetString("Points_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с индикатором точек.
        /// </summary>
        internal static string Points_indicator_link {
            get {
                return ResourceManager.GetString("Points_indicator_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество точек.
        /// </summary>
        internal static string Points_quantity {
            get {
                return ResourceManager.GetString("Points_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычисление корней многочлена.
        /// </summary>
        internal static string Polynom_roots {
            get {
                return ResourceManager.GetString("Polynom_roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропорциональный.
        /// </summary>
        internal static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питон код.
        /// </summary>
        internal static string Python_code {
            get {
                return ResourceManager.GetString("Python_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шкала радуги.
        /// </summary>
        internal static string Rainbow_scale {
            get {
                return ResourceManager.GetString("Rainbow_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генератор случайных чисел.
        /// </summary>
        internal static string Random_generator {
            get {
                return ResourceManager.GetString("Random_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ранг =.
        /// </summary>
        internal static string Rank_EQUALS {
            get {
                return ResourceManager.GetString("Rank_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение/Запись.
        /// </summary>
        internal static string ReadFRACTIONWrite {
            get {
                return ResourceManager.GetString("ReadFRACTIONWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реальное время.
        /// </summary>
        internal static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правая граница.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правая часть.
        /// </summary>
        internal static string Right_part {
            get {
                return ResourceManager.GetString("Right_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить данные?.
        /// </summary>
        internal static string Save_dataQUERY {
            get {
                return ResourceManager.GetString("Save_dataQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить график.
        /// </summary>
        internal static string Save_graph {
            get {
                return ResourceManager.GetString("Save_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить график.
        /// </summary>
        internal static string Save_graph_as {
            get {
                return ResourceManager.GetString("Save_graph_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить протоколы.
        /// </summary>
        internal static string Save_logs {
            get {
                return ResourceManager.GetString("Save_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите константы.
        /// </summary>
        internal static string Select_constants {
            get {
                return ResourceManager.GetString("Select_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простая переменная.
        /// </summary>
        internal static string Simple_variable {
            get {
                return ResourceManager.GetString("Simple_variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходные цвета.
        /// </summary>
        internal static string Source_colors {
            get {
                return ResourceManager.GetString("Source_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квадрат.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утойчивая система.
        /// </summary>
        internal static string Stable_system {
            get {
                return ResourceManager.GetString("Stable_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало.
        /// </summary>
        internal static string Start_step {
            get {
                return ResourceManager.GetString("Start_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время старта.
        /// </summary>
        internal static string Start_time {
            get {
                return ResourceManager.GetString("Start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечный автомат.
        /// </summary>
        internal static string State_machine {
            get {
                return ResourceManager.GetString("State_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовые файлы|*.txt.
        /// </summary>
        internal static string Text_files_ORSTARPOINTtxt {
            get {
                return ResourceManager.GetString("Text_files_ORSTARPOINTtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пороговый переключатель.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пороговый параметр.
        /// </summary>
        internal static string Threshold_parameter {
            get {
                return ResourceManager.GetString("Threshold_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип переключателя.
        /// </summary>
        internal static string Threshold_type {
            get {
                return ResourceManager.GetString("Threshold_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пороговое значение.
        /// </summary>
        internal static string Threshold_value {
            get {
                return ResourceManager.GetString("Threshold_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время (UTC) .
        /// </summary>
        internal static string Time_BRAUTCKET {
            get {
                return ResourceManager.GetString("Time_BRAUTCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг индикации времени.
        /// </summary>
        internal static string Time_indication_step {
            get {
                return ResourceManager.GetString("Time_indication_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временной интервал.
        /// </summary>
        internal static string Time_span {
            get {
                return ResourceManager.GetString("Time_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временной интервал (мс).
        /// </summary>
        internal static string Time_span_BRAmsKET {
            get {
                return ResourceManager.GetString("Time_span_BRAmsKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масштаб времени.
        /// </summary>
        internal static string Time_unit {
            get {
                return ResourceManager.GetString("Time_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верхняя граница.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренинг.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трансформация двумерного образа.
        /// </summary>
        internal static string Transformation_of_image {
            get {
                return ResourceManager.GetString("Transformation_of_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все цвета определены.
        /// </summary>
        internal static string Undefined_colors {
            get {
                return ResourceManager.GetString("Undefined_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вверх.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вектор.
        /// </summary>
        internal static string Vector {
            get {
                return ResourceManager.GetString("Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вертикальный.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web Службы.
        /// </summary>
        internal static string Web_Services {
            get {
                return ResourceManager.GetString("Web_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Веса.
        /// </summary>
        internal static string Weights {
            get {
                return ResourceManager.GetString("Weights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ось X.
        /// </summary>
        internal static string X_DEFIS_axis {
            get {
                return ResourceManager.GetString("X_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xml файлы|*.xml|Файлы данных|*.ds.
        /// </summary>
        internal static string Xml_FilesORSTARPOINTxmlORData_set_filesORSTARPOINTds {
            get {
                return ResourceManager.GetString("Xml_FilesORSTARPOINTxmlORData_set_filesORSTARPOINTds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ось Y.
        /// </summary>
        internal static string Y_DEFIS_axis {
            get {
                return ResourceManager.GetString("Y_DEFIS_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарушена последовательность информационных связей..
        /// </summary>
        internal static string You_should_create_measurements_source_before_consumer {
            get {
                return ResourceManager.GetString("You_should_create_measurements_source_before_consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
