-- MySQL Script generated by MySQL Workbench
-- Tue Jul 29 20:51:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema mysqlwarehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mysqlwarehouse` ;

-- -----------------------------------------------------
-- Schema mysqlwarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mysqlwarehouse` DEFAULT CHARACTER SET utf8mb3 ;
SHOW WARNINGS;
USE `mysqlwarehouse` ;

-- -----------------------------------------------------
-- Table `binarytable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binarytable` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `binarytable` (
  `Id` BIGINT UNSIGNED NOT NULL,
  `ParentId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` TEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `Extension` TEXT NOT NULL,
  `Data` BLOB NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_UNIQUE` ON `binarytable` (`Id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `binarytree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binarytree` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `binarytree` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ParentId` BIGINT UNSIGNED NOT NULL,
  `Name` TEXT NOT NULL,
  `Description` TEXT NOT NULL,
  `Extension` TEXT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_UNIQUE` ON `binarytree` (`Id` ASC) VISIBLE;

SHOW WARNINGS;
USE `mysqlwarehouse` ;

-- -----------------------------------------------------
-- procedure fiction
-- -----------------------------------------------------

USE `mysqlwarehouse`;
DROP procedure IF EXISTS `fiction`;
SHOW WARNINGS;

DELIMITER $$
USE `mysqlwarehouse`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `fiction`()
BEGIN

END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure insert_root
-- -----------------------------------------------------

USE `mysqlwarehouse`;
DROP procedure IF EXISTS `insert_root`;
SHOW WARNINGS;

DELIMITER $$
USE `mysqlwarehouse`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_root`(Name text, description text, extension text)
BEGIN
declare id bigint;
set id = LAST_INSERT_ID() + 1;
INSERT INTO `binarytree`
(`Id`,
`ParentId`,
`Name`,
`Description`,
`Extension`)
VALUES (
id,
id,
Name,
description,
extension);
select id;
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure insert_table
-- -----------------------------------------------------

USE `mysqlwarehouse`;
DROP procedure IF EXISTS `insert_table`;
SHOW WARNINGS;

DELIMITER $$
USE `mysqlwarehouse`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_table`(ParentId bigint, Name text, description text, extension text, data blob, id bigint)
BEGIN
declare id bigint;
set id = LAST_INSERT_ID() + 1;
INSERT INTO `binarytable`
(`Id`,
`ParentId`,
`Name`,
`Description`,
`Extension`,
`Data`)
VALUES (
id,
ParentId,
Name,
description,
extension,
data);
select id;
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- procedure insert_tree
-- -----------------------------------------------------

USE `mysqlwarehouse`;
DROP procedure IF EXISTS `insert_tree`;
SHOW WARNINGS;

DELIMITER $$
USE `mysqlwarehouse`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_tree`(PareantId bigint, Name text, description text, extension text)
BEGIN
declare id bigint;
set id = LAST_INSERT_ID() + 1;
INSERT INTO `binarytree`
(`Id`,
`ParentId`,
`Name`,
`Description`,
`Extension`)
VALUES (
id,
ParentId,
Name,
description,
extension);
select id;
END$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `tablew`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `tablew` ;
SHOW WARNINGS;
USE `mysqlwarehouse`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tablew` AS select `binarytable`.`Id` AS `Id`,`binarytable`.`ParentId` AS `ParentId`,`binarytable`.`Name` AS `Name`,`binarytable`.`Extension` AS `Extension` from `binarytable`;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
