//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectFormulaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProjectFormulaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.BracketsSymbol&quot; symbol=&quot;P&quot; S=&quot;( )&quot; Type=&quot;2&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;P&quot;&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;a&quot; S=&quot;a&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///            &lt;F /&gt;
        ///          &lt;/S&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;s&quot; S=&quot;sin&quot; Type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;x&quot; S=&quot;x&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.BinarySymbol&quot; symbol=&quot;+&quot; S=&quot;+&quot; Type=&quot;3&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot; /&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;y&quot; S=&quot;y&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinaryDouble {
            get {
                return ResourceManager.GetString("BinaryDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;a&quot; S=&quot;a&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.BinarySymbol&quot; symbol=&quot;∖&quot; S=&quot;AND&quot; Type=&quot;3&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot; /&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;b&quot; S=&quot;b&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleVa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinaryLogical {
            get {
                return ResourceManager.GetString("BinaryLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;&apos;&quot; S=&quot;d/dt&quot; Type=&quot;4&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;c&quot; S=&quot;cos&quot; Type=&quot;4&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;s&quot; S=&quot;sin&quot; Type=&quot;4&quot; Index=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DerivationsCalc {
            get {
                return ResourceManager.GetString("DerivationsCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.BracketsSymbol&quot; symbol=&quot;P&quot; S=&quot;( )&quot; Type=&quot;2&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;P&quot;&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;a&quot; S=&quot;a&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///            &lt;F /&gt;
        ///          &lt;/S&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;s&quot; S=&quot;sin&quot; Type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Formulas {
            get {
                return ResourceManager.GetString("Formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;0&quot; S=&quot;0&quot; Type=&quot;5&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///    &lt;/F&gt;
        ///  &lt;/R&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;1&quot; S=&quot;1&quot; Type=&quot;5&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///    &lt;/F&gt;
        ///  &lt;/R&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NullaryDouble {
            get {
                return ResourceManager.GetString("NullaryDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.BracketsSymbol&quot; symbol=&quot;P&quot; S=&quot;( )&quot; Type=&quot;2&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;P&quot;&gt;
        ///        &lt;F&gt;
        ///          &lt;S type=&quot;FormulaEditor.Symbols.BracketsSymbol&quot; symbol=&quot;P&quot; S=&quot;( )&quot; Type=&quot;2&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;P&quot;&gt;
        ///            &lt;F&gt;
        ///              &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;x&quot; S=&quot;x&quot; Type=&quot;1&quot; Index=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TernaryDouble {
            get {
                return ResourceManager.GetString("TernaryDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;s&quot; S=&quot;sin&quot; Type=&quot;4&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;0&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSymbol&quot; symbol=&quot;x&quot; S=&quot;x&quot; Type=&quot;1&quot; Index=&quot;1&quot; Level=&quot;0&quot; DoubleValue=&quot;0&quot; UlongValue=&quot;0&quot; Italic=&quot;1&quot; Bold=&quot;1&quot; Sb=&quot;&quot;&gt;
        ///        &lt;F /&gt;
        ///      &lt;/S&gt;
        ///    &lt;/F&gt;
        ///  &lt;/R&gt;
        ///  &lt;R&gt;
        ///    &lt;F&gt;
        ///      &lt;S type=&quot;FormulaEditor.Symbols.SimpleSym [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnaryDouble {
            get {
                return ResourceManager.GetString("UnaryDouble", resourceCulture);
            }
        }
    }
}
